name: Cross-browser test
on: [push]
jobs:
    browser-test:
        name: Run tests on ${{ matrix.env-conf.browser }}
        strategy:
            matrix:
                env-conf:
                    - browser: chrome
                      os: windows-latest
                    - browser: firefox
                      os: windows-latest
                    - browser: safari
                      os: macos-latest
                    # IE browser interop seems to be broken on Selenium 4
                    #- browser: ie
                    #  os: windows-latest
        runs-on: ${{ matrix.env-conf.os }}
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 15
            - run: npm ci
              env:
                  DETECT_CHROMEDRIVER_VERSION: true
            - run: npm run test:browser
              env:
                  BROWSER: ${{ matrix.env-conf.browser }}
